name: Roblox Events

on:
  workflow_dispatch:

  on:
  schedule:
    - cron: "* * * * *"

permissions:
  contents: write

jobs:
  check-events:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requests
        run: pip install requests

      - name: Run Roblox Events
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          CONTROL_WEBHOOK: ${{ secrets.CONTROL_WEBHOOK }}
        run: python main.py

      - name: Save event state
        run: |

          git config user.name "Roblox Events Bot"

          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add events_state.json alerts_state.json stats_state.json control_state.json

          if git diff --cached --quiet; then

            echo "No state changes."

          else

            git commit -m "Update Roblox bot state"

            git push

          fi
